name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Realizar despliegue en Render
          response=$(curl -X POST "https://api.render.com/v1/services/srv-d084vu7gi27c7385mcq0/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY")
          
          
          echo "Despliegue iniciado. URL de la aplicación: https://research01-885-u1.onrender.com/"
