name: Deploy to Render

on:
  push:
    branches:
      - main  # Puedes cambiar esto por cualquier otra rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Asegúrate de usar la versión que tu app necesita
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Agrega tu API key a los secretos de GitHub
        run: |
          curl -X POST "https://api.render.com/v1/services/<tu-service-id>/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY"
